name: FootHill

services:
  # MongoDB service
  database:
    image: mongo:8.0.0
    container_name: database
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - foothill-network

  # Express API service
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://database:27017
    depends_on:
      database:
        condition: service_healthy
    networks:
      - foothill-network

  # React Web UI
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8080:80"
    environment:
      - VITE_API_BASE_URL=http://api:3000
    depends_on:
      - api
    networks:
      - foothill-network

volumes:
  mongo-data:

networks:
  foothill-network:
    driver: bridge
